class_name Township
extends Node3D
## Ashapurna Township (Sheoganj): an original, to-scale, data-driven gated colony dropped onto the
## OSM world at a lat/lon anchor + rotation (data/township/ashapurna.json, generated by
## tools/gen_ashapurna.py). Local frame: u = right when driving in through the gate, v = depth inward.
## This node's transform maps township-local (x = u, z = -v) into world space, so local forward (-Z) = inward.

const WALL := Color("e9d68e")
const WALL_CAP := Color("c9a94a")
const CREAM := Color("f1e6b8")
const YELLOW := Color("f2c94c")
const CONCRETE := Color("9d9a92")
const BRICK := Color("b5603f")
const SAND := Color("c9b080")
const AX := [Vector3.RIGHT, Vector3.UP, Vector3.BACK]

var d: Dictionary
var w: OsmWorld
var gate_w := Vector2.ZERO      # gate centre in world metres
var bearing := 0.0              # radians, direction driven INTO the township (compass, clockwise from north)
var U := Vector2.RIGHT          # world direction of +u
var N := Vector2.UP             # world direction of +v (inward)
var half_w := 160.0
var depth := 390.0
var circuit_pts: Array = []     # [[u,v], ...] closed racing circuit centre line
var _rng := RandomNumberGenerator.new()
var _solid: SurfaceTool
var _mat_solid: StandardMaterial3D

static func load_data(path: String) -> Dictionary:
	var v = JSON.parse_string(FileAccess.get_file_as_string(path))
	return v if v is Dictionary else {}

func setup(world: OsmWorld, data: Dictionary) -> void:
	w = world
	d = data
	var a: Dictionary = d["anchor"]
	var c: Array = w.world["center"]
	var mx := 111320.0 * cos(deg_to_rad(float(c[0])))
	gate_w = Vector2((float(a["lon"]) - float(c[1])) * mx, -(float(a["lat"]) - float(c[0])) * 110574.0)
	bearing = deg_to_rad(float(a["rotation_deg"]))
	N = Vector2(sin(bearing), -cos(bearing))
	U = Vector2(cos(bearing), sin(bearing))
	half_w = float(d["size"]["half_width"])
	depth = float(d["size"]["depth"])
	position = Vector3(gate_w.x, 0.0, gate_w.y)
	rotation.y = -bearing
	circuit_pts = d["circuit"]["line"]
	_rng.seed = 20261009

# ------------------------------------------------------------------ frame helpers
func world2(u: float, v: float) -> Vector2:
	return gate_w + U * u + N * v

func to_local_uv(p: Vector2) -> Vector2:
	var q := p - gate_w
	return Vector2(q.dot(U), q.dot(N))

func world3(u: float, v: float, y := 0.0) -> Vector3:
	var p := world2(u, v)
	return Vector3(p.x, y, p.y)

func inside(p: Vector2, margin := 4.0) -> bool:
	var q := to_local_uv(p)
	return absf(q.x) <= half_w + margin and q.y >= -65.0 and q.y <= depth + margin + 8.0

func yaw_world(local_yaw: float) -> float:
	return local_yaw - bearing

func P(u: float, y: float, v: float) -> Vector3:
	return Vector3(u, y, -v)

func circuit_world() -> PackedVector3Array:
	var out := PackedVector3Array()
	for p in circuit_pts:
		var q := world2(float(p[0]), float(p[1]))
		out.append(Vector3(q.x, 0.0, q.y))
	return out

## Start-grid transforms (world) for racer slot i: two abreast, staggered, behind the start line.
func grid_transform(i: int) -> Transform3D:
	var rows: Array = d["circuit"]["grid_rows_v"]
	var row := i / 2
	var side := i % 2
	var u := -5.0 + (-2.0 if side == 0 else 2.0)
	var v := float(rows[mini(row, rows.size() - 1)]) - (0.0 if side == 0 else 3.5)
	var p := world3(u, v, 0.65)
	var yaw := atan2(-N.x, -N.y)
	return Transform3D(Basis(Vector3.UP, yaw), p)

func spawn_xz_dir() -> Array:
	return [world2(-5.0, -30.0), N]

# ------------------------------------------------------------------ gen integration (houses, trees, poles ...)
func integrate_gen(gen: Dictionary) -> void:
	for key in ["buildings", "trees", "poles", "stars", "lights"]:
		var src: Array = gen.get(key, [])
		gen[key] = src.filter(func(e): return not inside(Vector2(float(e[0]), float(e[1]))))
	gen["wires"] = (gen.get("wires", []) as Array).filter(func(e): return not inside(Vector2(float(e[0]), float(e[1]))))
	var b: Array = gen["buildings"]
	for p in d["plots"]:
		if p["kind"] != "house":
			continue
		var f := float(p["facing"])
		var pw := float(p["w"]) - 3.0
		var pd := float(p["d"]) - 5.0
		var c := world2(float(p["u"]), float(p["v"]) - f * 0.5)
		var front := N * f
		var seed_i := int(p["seed"])
		b.append([c.x, c.y, atan2(front.x, front.y), pw, pd, int(p["floors"]), int(p["palette"]), 0, seed_i % 2, 0])
	var a: Dictionary = d["apartment"]
	var t: Array = gen["trees"]
	for e in d["trees"]:
		var q := world2(float(e[0]), float(e[1]))
		t.append([q.x, q.y, float(e[2]), int(e[3]), int(e[4])])
	for e in d["poles"]:
		var q := world2(float(e[0]), float(e[1]))
		gen["poles"].append([q.x, q.y])
	for e in d["wires"]:
		var q1 := world2(float(e[0]), float(e[1]))
		var q2 := world2(float(e[2]), float(e[3]))
		gen["wires"].append([q1.x, q1.y, q2.x, q2.y])
	for e in d["lights"]:
		var q := world2(float(e[0]), float(e[1]))
		gen["lights"].append([q.x, q.y, yaw_world(float(e[2]))])
	for e in d["stars"]:
		var q := world2(float(e[0]), float(e[1]))
		gen["stars"].append([q.x, q.y])

## Registers every township road with the world's drivable-segment index + minimap list.
func register_roads() -> void:
	for r in d["roads"]:
		var pts: Array = r["pts"]
		var pv := PackedVector2Array()
		for p in pts:
			pv.append(world2(float(p[0]), float(p[1])))
		var wd := float(r["w"])
		if r.get("closed", false) and pv.size() > 1 and pv[0] != pv[pv.size() - 1]:
			pv.append(pv[0])
		w.road_polylines.append({"pts": pv, "w": wd, "c": "residential"})
		for i in pv.size() - 1:
			w._add_seg(pv[i], pv[i + 1], wd * 0.5)
	# paver forecourt: several parallel centre-lines so every part of it counts as drivable
	var fc: Dictionary = d["forecourt"]
	for uu: float in [-30.0, -10.0, 10.0, 30.0]:
		w._add_seg(world2(uu, -67.0), world2(uu, 0.0), 12.0)

# ------------------------------------------------------------------ build
func build() -> void:
	_solid = SurfaceTool.new()
	_solid.begin(Mesh.PRIMITIVE_TRIANGLES)
	_mat_solid = StandardMaterial3D.new()
	_mat_solid.vertex_color_use_as_albedo = true
	_mat_solid.roughness = 0.9
	_mat_solid.cull_mode = BaseMaterial3D.CULL_DISABLED
	_ground_and_roads()
	_forecourt()
	_circuit_furniture()
	_gate()
	_walls()
	_plots()
	_apartment()
	_playground()
	_garden_temple()
	_median()
	_cars()
	_hills()
	var mesh := _solid.commit()
	if mesh != null and mesh.get_surface_count() > 0:
		var mi := MeshInstance3D.new()
		mi.mesh = mesh
		mi.material_override = _mat_solid
		add_child(mi)

# --- primitives
func _box(c: Vector3, s: Vector3, col: Color, yaw := 0.0, roll := 0.0, st: SurfaceTool = null) -> void:
	var t := st if st != null else _solid
	var bs := Basis(Vector3.UP, yaw) * Basis(Vector3.BACK, roll)
	var h := s * 0.5
	for i in 3:
		var n: Vector3 = AX[i]
		var a: Vector3 = AX[(i + 1) % 3]
		var b: Vector3 = AX[(i + 2) % 3]
		for sg: float in [-1.0, 1.0]:
			var nn: Vector3 = n * sg
			var cs: Array[Vector3] = [(nn - a - b) * h, (nn + a - b) * h, (nn + a + b) * h, (nn - a + b) * h]
			var nrm := bs * nn
			for k in [0, 1, 2, 0, 2, 3]:
				t.set_color(col)
				t.set_normal(nrm)
				t.add_vertex(c + bs * cs[k])

func _quad(a: Vector2, b: Vector2, width: float, y: float, col: Color) -> void:
	var dv := b - a
	if dv.length() < 0.01:
		return
	var n := Vector2(-dv.y, dv.x).normalized() * width * 0.5
	var pts := [a + n, b + n, b - n, a - n]
	for k in [0, 1, 2, 0, 2, 3]:
		_solid.set_color(col)
		_solid.set_normal(Vector3.UP)
		_solid.add_vertex(Vector3(pts[k].x, y, pts[k].y))

func _rect_flat(u0: float, v0: float, u1: float, v1: float, y: float, col: Color) -> void:
	var pts := [Vector2(u0, -v0), Vector2(u1, -v0), Vector2(u1, -v1), Vector2(u0, -v1)]
	for k in [0, 1, 2, 0, 2, 3]:
		_solid.set_color(col)
		_solid.set_normal(Vector3.UP)
		_solid.add_vertex(Vector3(pts[k].x, y, pts[k].y))

func _coll(u: float, y: float, v: float, sx: float, sy: float, sz: float, yaw := 0.0) -> void:
	w._add_box_collider(transform * P(u, y, v), Vector3(sx, sy, sz), rotation.y + yaw)

func _mi(mesh: Mesh, mat: Material, pos: Vector3, shadow := true) -> MeshInstance3D:
	var m := MeshInstance3D.new()
	m.mesh = mesh
	m.material_override = mat
	m.position = pos
	if not shadow:
		m.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	add_child(m)
	return m

func _text(txt: String, pos: Vector3, size: float, col: Color, back := false) -> void:
	var l := Label3D.new()
	l.text = txt
	l.pixel_size = size
	l.font_size = 96
	l.outline_size = 0
	l.modulate = col
	l.shaded = false
	l.double_sided = false
	l.position = pos
	if back:
		l.rotation.y = PI
	add_child(l)

func _surf(st: SurfaceTool, mat: Material) -> void:
	var mesh := st.commit()
	if mesh == null or mesh.get_surface_count() == 0:
		return
	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.material_override = mat
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	add_child(mi)

# --- ground, roads
func _ground_and_roads() -> void:
	var g := SurfaceTool.new(); g.begin(Mesh.PRIMITIVE_TRIANGLES)
	var pts := [Vector2(-half_w - 3.0, 0.0), Vector2(half_w + 3.0, 0.0), Vector2(half_w + 3.0, -depth - 3.0), Vector2(-half_w - 3.0, -depth - 3.0)]
	for k in [0, 1, 2, 0, 2, 3]:
		g.set_normal(Vector3.UP)
		g.set_uv(pts[k] / 6.0)
		g.add_vertex(Vector3(pts[k].x, 0.045, pts[k].y))
	_surf(g, w._pbr("ground037", 6.0, Color("d3bf93")))
	var asphalt := SurfaceTool.new(); asphalt.begin(Mesh.PRIMITIVE_TRIANGLES)
	for r in d["roads"]:
		if r["kind"] == "forecourt":
			continue
		var pv := PackedVector2Array()
		for p in r["pts"]:
			pv.append(Vector2(float(p[0]), -float(p[1])))
		if r.get("closed", false) and pv.size() > 1 and pv[0] != pv[pv.size() - 1]:
			pv.append(pv[0])
		w._ribbon(asphalt, pv, float(r["w"]), 0.10, 1.0 / 5.0)
	_surf(asphalt, w._pbr("asphalt031", 5.0, Color("b9b6b0")))

func _forecourt() -> void:
	var fc: Dictionary = d["forecourt"]
	var img := Image.create(192, 192, false, Image.FORMAT_RGB8)
	var bands := [Color("c9919a"), Color("84363f"), Color("d6c6a2")]
	for y in 192:
		for x in 192:
			var band := int(((x + y) % 192) / 64) % 3
			var col: Color = bands[band]
			var row := y / 8
			var xo := x + (8 if row % 2 == 1 else 0)
			if y % 8 == 0 or xo % 16 == 0:
				col = col.darkened(0.16)
			else:
				col = col.darkened(((x * 7 + y * 13) % 11) * 0.006)
			img.set_pixel(x, y, col)
	img.generate_mipmaps()
	var tex := ImageTexture.create_from_image(img)
	var m := StandardMaterial3D.new()
	m.albedo_texture = tex
	m.roughness = 0.85
	m.uv1_scale = Vector3.ONE / 3.0
	m.texture_filter = BaseMaterial3D.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS_ANISOTROPIC
	var st := SurfaceTool.new(); st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var u0 := float(fc["u0"]); var u1 := float(fc["u1"]); var v0 := -65.0; var v1 := float(fc["v1"])
	var pts := [Vector2(u0, -v0), Vector2(u1, -v0), Vector2(u1, -v1), Vector2(u0, -v1)]
	for k in [0, 2, 1, 0, 3, 2]:
		st.set_normal(Vector3.UP)
		st.set_uv(pts[k])
		st.add_vertex(Vector3(pts[k].x, 0.12, pts[k].y))
	_surf(st, m)

func _circuit_furniture() -> void:
	var c: Dictionary = d["circuit"]
	# red-white kerbs
	for k in c["kerbs"]:
		var col := Color("d8262c") if int(k[4]) == 0 else Color("f4f4f0")
		_quad(Vector2(k[0], -float(k[1])), Vector2(k[2], -float(k[3])), 1.0, 0.145, col)
	# start / finish line (chequered) + grid boxes
	for ix in 16:
		for iz in 2:
			var col := Color.BLACK if (ix + iz) % 2 == 0 else Color.WHITE
			_rect_flat(-9.0 + ix * 0.5, -8.0 + iz * 0.5, -8.5 + ix * 0.5, -7.5 + iz * 0.5, 0.14, col)
	var rows: Array = c["grid_rows_v"]
	for i in 5:
		var tf := grid_transform(i)
		var q := to_local_uv(Vector2(tf.origin.x, tf.origin.z))
		_rect_flat(q.x - 1.1, q.y - 2.4, q.x + 1.1, q.y - 2.25, 0.14, Color.WHITE)
		_rect_flat(q.x - 1.1, q.y - 2.4, q.x - 0.95, q.y + 0.6, 0.14, Color.WHITE)
		_rect_flat(q.x + 0.95, q.y - 2.4, q.x + 1.1, q.y + 0.6, 0.14, Color.WHITE)
	# start/finish gantry
	for pu: float in [-10.5, 0.5]:
		_box(P(pu, 3.2, -8.0), Vector3(0.5, 6.4, 0.5), Color("7a1f2b"))
		_coll(pu, 3.2, -8.0, 0.5, 6.4, 0.5)
	_box(P(-5.0, 6.4, -8.0), Vector3(12.0, 1.1, 0.4), Color("f4f4f0"))
	_box(P(-5.0, 6.4, -8.0), Vector3(12.1, 0.25, 0.42), Color("d8262c"))
	_text("START / FINISH", P(-5.0, 6.45, -8.25), 0.014, Color("1c2a3a"))
	_text("START / FINISH", P(-5.0, 6.45, -7.75), 0.014, Color("1c2a3a"), true)
	# tyre barriers (stacks) in black with red/white tops
	var bx: Array = []
	var tops_r: Array = []
	var tops_w: Array = []
	var i := 0
	for b in c["barriers"]:
		var xf := transform * Transform3D(Basis(Vector3.UP, 0.0), P(float(b[0]), 0.0, float(b[1])))
		var base := xf * Vector3(0, 0.45, 0)
		bx.append(Transform3D(Basis.IDENTITY, base))
		var top := Transform3D(Basis.IDENTITY, base + Vector3(0, 0.5, 0))
		if i % 2 == 0:
			tops_r.append(top)
		else:
			tops_w.append(top)
		i += 1
		var cs := CollisionShape3D.new()
		var sh := CylinderShape3D.new()
		sh.radius = 0.55
		sh.height = 1.0
		cs.shape = sh
		cs.position = base
		w._col_body.add_child(cs)
	var cyl := CylinderMesh.new(); cyl.top_radius = 0.55; cyl.bottom_radius = 0.55; cyl.height = 0.9; cyl.radial_segments = 10
	var cap := CylinderMesh.new(); cap.top_radius = 0.56; cap.bottom_radius = 0.56; cap.height = 0.1; cap.radial_segments = 10
	w._instances(cyl, bx, w._flat_mat(Color("1b1b1d"), 0.9), Callable())
	w._instances(cap, tops_r, w._flat_mat(Color("d8262c"), 0.7), Callable())
	w._instances(cap.duplicate(), tops_w, w._flat_mat(Color("f4f4f0"), 0.7), Callable())

# --- gate, gatehouses, walls
func _gate() -> void:
	var g: Dictionary = d["gate"]
	var half := float(g["opening"]) * 0.5
	var ph := float(g["pillar_h"])
	for s: float in [-1.0, 1.0]:
		var pu: float = s * (half + 1.6)
		_box(P(pu, ph * 0.5, 0.0), Vector3(3.2, ph, 3.2), CREAM)
		_box(P(pu, 1.0, 0.0), Vector3(3.5, 2.0, 3.5), YELLOW)
		_box(P(pu, ph * 0.55, 0.0), Vector3(3.4, 0.5, 3.4), YELLOW)
		_box(P(pu, ph + 0.3, 0.0), Vector3(4.0, 0.6, 4.0), WALL_CAP)
		_box(P(pu, ph + 0.9, 0.0), Vector3(2.4, 0.6, 2.4), CREAM)
		_coll(pu, ph * 0.5, 0.0, 3.4, ph, 3.4)
	_box(P(0.0, ph - 0.2, 0.0), Vector3(float(g["opening"]) + 0.2, 1.2, 1.6), CREAM)
	var segs := 12
	for k in segs:
		var t0 := -1.0 + 2.0 * k / segs
		var t1 := -1.0 + 2.0 * (k + 1) / segs
		var y0 := ph + 0.4 + 2.2 * sqrt(maxf(0.0, 1.0 - t0 * t0))
		var y1 := ph + 0.4 + 2.2 * sqrt(maxf(0.0, 1.0 - t1 * t1))
		var cu := (t0 + t1) * 0.5 * half
		var seg_len := sqrt(pow((t1 - t0) * half, 2) + pow(y1 - y0, 2)) + 0.05
		_box(P(cu, (y0 + y1) * 0.5, 0.0), Vector3(seg_len, 0.9, 1.2), YELLOW if k % 2 == 0 else CREAM, 0.0, atan2(y1 - y0, (t1 - t0) * half))
	_box(P(0.0, ph + 1.6, 0.0), Vector3(14.0, 2.6, 0.5), Color("5b1a22"))
	_box(P(0.0, ph + 1.6, 0.0), Vector3(14.4, 0.2, 0.6), WALL_CAP)
	_text(str(g["name"]), P(0.0, ph + 2.0, -0.35), 0.0115, Color("f6e7b0"))
	_text(str(g["sub"]), P(0.0, ph + 0.95, -0.35), 0.0085, Color("f6e7b0"))
	_text(str(g["name"]), P(0.0, ph + 2.0, 0.35), 0.0115, Color("f6e7b0"), true)
	_text(str(g["sub"]), P(0.0, ph + 0.95, 0.35), 0.0085, Color("f6e7b0"), true)
	for gh in d["gatehouses"]:
		var gu := float(gh["u"]); var gv := float(gh["v"]); var gw := float(gh["w"]); var gd := float(gh["d"])
		_box(P(gu, 1.75, gv + gd * 0.5), Vector3(gw, 3.5, gd), CREAM)
		_box(P(gu, 0.4, gv + gd * 0.5), Vector3(gw + 0.2, 0.8, gd + 0.2), YELLOW)
		_box(P(gu, 3.65, gv + gd * 0.5), Vector3(gw + 1.4, 0.3, gd + 1.4), WALL_CAP)
		_box(P(gu, 3.95, gv + gd * 0.5), Vector3(gw - 1.0, 0.4, gd - 1.0), CREAM)
		var inner := -signf(gu)
		for wv: float in [gv + 2.2, gv + 5.0, gv + 7.8]:
			_box(P(gu + inner * (gw * 0.5 + 0.02), 2.0, wv), Vector3(0.1, 1.2, 1.3), Color("33414f"))
		_box(P(gu, 1.5, gv - 0.02), Vector3(1.6, 2.4, 0.12), Color("5b3b25"))
		_coll(gu, 2.0, gv + gd * 0.5, gw, 4.0, gd)

func _walls() -> void:
	for wl in d["walls"]:
		var a := Vector2(float(wl["a"][0]), float(wl["a"][1]))
		var b := Vector2(float(wl["b"][0]), float(wl["b"][1]))
		var mid := (a + b) * 0.5
		var length := a.distance_to(b)
		var along_u := absf(b.x - a.x) > absf(b.y - a.y)
		var sz := Vector3(length, 2.2, 0.4) if along_u else Vector3(0.4, 2.2, length)
		_box(P(mid.x, 1.1, mid.y), sz, WALL)
		_box(P(mid.x, 2.25, mid.y), Vector3(sz.x + (0.2 if along_u else 0.15), 0.18, sz.z + (0.15 if along_u else 0.2)), WALL_CAP)
		_coll(mid.x, 1.1, mid.y, sz.x, 2.4, sz.z)
		var n := int(length / 12.0)
		for k in range(0, n + 1):
			var t := float(k) / maxf(n, 1)
			var p := a.lerp(b, t)
			_box(P(p.x, 1.35, p.y), Vector3(0.75, 2.7, 0.75), WALL_CAP.lightened(0.1))

# --- plots
func _plots() -> void:
	var scrub_xf := {"plant_bush": [], "rock_smallA": [], "plant_bushLarge": []}
	for p in d["plots"]:
		var pu := float(p["u"]); var pv := float(p["v"]); var pw := float(p["w"]); var pd := float(p["d"])
		var f := float(p["facing"])
		var seed_i := int(p["seed"])
		_rng.seed = seed_i
		match p["kind"]:
			"empty":
				var tint := Color(0.78 + _rng.randf() * 0.05, 0.68 + _rng.randf() * 0.04, 0.5 + _rng.randf() * 0.05)
				_rect_flat(pu - pw * 0.5 + 0.3, pv - pd * 0.5 + 0.3, pu + pw * 0.5 - 0.3, pv + pd * 0.5 - 0.3, 0.05, tint)
				if p.get("wall", false):
					for sg: float in [-1.0, 1.0]:
						_box(P(pu + sg * (pw * 0.5 - 0.15), 0.45, pv), Vector3(0.25, 0.9, pd - 0.6), WALL)
					_box(P(pu, 0.45, pv - f * (pd * 0.5 - 0.15)), Vector3(pw - 0.6, 0.9, 0.25), WALL)
				var nscr := _rng.randi_range(0, 4)
				for k in nscr:
					var lu := pu + _rng.randf_range(-pw * 0.4, pw * 0.4)
					var lv := pv + _rng.randf_range(-pd * 0.4, pd * 0.4)
					var kind := "plant_bush" if _rng.randf() < 0.7 else "rock_smallA"
					if _rng.randf() < 0.15:
						kind = "plant_bushLarge"
					var xf := transform * Transform3D(Basis(Vector3.UP, _rng.randf() * TAU).scaled(Vector3.ONE * _rng.randf_range(1.2, 2.2)), P(lu, 0.0, lv))
					(scrub_xf[kind] as Array).append(xf)
			"construction":
				_construction(p)
			"villa":
				_villa(p)
	for kind in scrub_xf:
		w._scatter("res://assets/kenney/nature/%s.glb" % kind, scrub_xf[kind])

func _construction(p: Dictionary) -> void:
	var pu := float(p["u"]); var pv := float(p["v"]) - float(p["facing"]) * 0.5
	var bw := float(p["w"]) - 3.0
	var bd := float(p["d"]) - 5.0
	var f := float(p["facing"])
	var floors := int(p["floors"])
	var built := clampi(int(ceil(floors * float(p["done"]))), 1, floors)
	var fh := 3.2
	var top := built * fh
	var rng := RandomNumberGenerator.new()
	rng.seed = int(p["seed"])
	_box(P(pu, 0.3, pv), Vector3(bw + 0.4, 0.6, bd + 0.4), CONCRETE.darkened(0.1))
	var cols_u := 3
	var cols_v := 3
	for i in cols_u:
		for j in cols_v:
			var cu := pu - bw * 0.5 + 0.4 + (bw - 0.8) * i / (cols_u - 1)
			var cv := pv - bd * 0.5 + 0.4 + (bd - 0.8) * j / (cols_v - 1)
			_box(P(cu, top * 0.5 + 0.3, cv), Vector3(0.4, top + 0.6, 0.4), CONCRETE)
			_box(P(cu, top + 1.0, cv), Vector3(0.07, 1.0, 0.07), Color("7a4a2a"))
	for k in range(1, built + 1):
		_box(P(pu, k * fh, pv), Vector3(bw, 0.22, bd), CONCRETE.lightened(0.05))
	for k in range(0, built - 1):
		var hh := fh - 0.25
		var y := k * fh + fh * 0.5 + 0.1
		_box(P(pu, y, pv - f * (bd * 0.5 - 0.1)), Vector3(bw - 0.4, hh, 0.22), BRICK)
		_box(P(pu - bw * 0.5 + 0.1, y, pv), Vector3(0.22, hh, bd - 0.4), BRICK)
	# scaffolding on the front face
	var sy := top + 0.5
	var front_v := pv + f * (bd * 0.5 + 0.8)
	var npole := int(bw / 2.4) + 1
	for i in npole:
		var cu := pu - bw * 0.5 + bw * i / maxf(npole - 1, 1)
		_box(P(cu, sy * 0.5, front_v), Vector3(0.08, sy, 0.08), Color("a07a3c"))
	for k in range(1, int(sy / 1.8) + 1):
		_box(P(pu, k * 1.8, front_v), Vector3(bw, 0.07, 0.07), Color("a07a3c"))
		if k % 2 == 0:
			_box(P(pu, k * 1.8 + 0.05, front_v - f * 0.35), Vector3(bw, 0.05, 0.7), Color("8a6a40"))
	# heaps of sand / bricks out front
	_box(P(pu + bw * 0.25, 0.5, pv + f * (bd * 0.5 + 2.6)), Vector3(2.4, 1.0, 2.0), SAND)
	_box(P(pu - bw * 0.25, 0.4, pv + f * (bd * 0.5 + 2.4)), Vector3(1.6, 0.8, 1.0), BRICK)
	_coll(pu, top * 0.5, pv, bw, top, bd)

func _villa(p: Dictionary) -> void:
	var pu := float(p["u"]); var pv := float(p["v"]) - float(p["facing"]) * 0.5
	var bw := float(p["w"]) - 3.5
	var bd := float(p["d"]) - 6.0
	var f := float(p["facing"])
	var pale := Color("f3e7a6")
	_box(P(pu, 0.35, pv), Vector3(bw + 0.5, 0.7, bd + 0.5), Color("d8c98a"))
	_box(P(pu, 2.3, pv), Vector3(bw, 3.2, bd), pale)
	# hip roof
	var rh := 2.4
	var ov := 0.9
	var hx := bw * 0.5 + ov
	var hz := bd * 0.5 + ov
	var rl := maxf(bw - bd, 0.4) * 0.5
	var ry := 3.9
	var c0 := Color("8a4a35")
	var corners := [Vector3(-hx, ry, -hz), Vector3(hx, ry, -hz), Vector3(hx, ry, hz), Vector3(-hx, ry, hz)]
	var ridge := [Vector3(-rl, ry + rh, 0), Vector3(rl, ry + rh, 0)]
	var tris := [
		[corners[0], corners[1], ridge[1]], [corners[0], ridge[1], ridge[0]],
		[corners[2], corners[3], ridge[0]], [corners[2], ridge[0], ridge[1]],
		[corners[1], corners[2], ridge[1]], [corners[3], corners[0], ridge[0]],
	]
	for t in tris:
		var nrm: Vector3 = ((t[1] - t[0]).cross(t[2] - t[0])).normalized()
		for q in t:
			_solid.set_color(c0)
			_solid.set_normal(nrm)
			_solid.add_vertex(P(pu, 0.0, pv) + q)
	# verandah on the front
	var fz := f * (bd * 0.5 + 1.4)
	_box(P(pu, 3.0, pv + fz), Vector3(bw * 0.8, 0.2, 2.6), Color("e9ddb0"))
	for sg: float in [-1.0, -0.33, 0.33, 1.0]:
		_box(P(pu + sg * bw * 0.36, 1.5, pv + fz + f * 1.1), Vector3(0.3, 3.0, 0.3), CREAM)
	for sg: float in [-1.0, 1.0]:
		_box(P(pu + sg * bw * 0.28, 2.0, pv + f * (bd * 0.5 + 0.03)), Vector3(1.3, 1.5, 0.1), Color("5c3d2a"))
	_coll(pu, 2.5, pv, bw, 5.0, bd)

func _apartment() -> void:
	var a: Dictionary = d["apartment"]
	var au := float(a["u"]); var av := float(a["v"])
	var aw := float(a["w"]); var ad := float(a["d"])
	var floors := int(a["floors"])
	var f := float(a["facing"])
	var fh := 3.2
	var built := floors
	var top := built * fh
	_box(P(au, 0.4, av), Vector3(aw + 1.0, 0.8, ad + 1.0), CONCRETE.darkened(0.15))
	var ncu := 7
	var ncv := 3
	for i in ncu:
		for j in ncv:
			var cu := au - aw * 0.5 + 0.5 + (aw - 1.0) * i / (ncu - 1)
			var cv := av - ad * 0.5 + 0.5 + (ad - 1.0) * j / (ncv - 1)
			_box(P(cu, top * 0.5, cv), Vector3(0.55, top, 0.55), CONCRETE)
			_box(P(cu, top + 1.1, cv), Vector3(0.08, 1.4, 0.08), Color("7a4a2a"))
	for k in range(1, floors + 1):
		_box(P(au, k * fh, av), Vector3(aw, 0.28, ad), CONCRETE.lightened(0.06))
	# brick infill on the lower three floors (back + side), open frame above
	for k in range(0, 3):
		var y := k * fh + fh * 0.5
		_box(P(au, y, av - f * (ad * 0.5 - 0.15)), Vector3(aw - 0.4, fh - 0.3, 0.25), BRICK)
		_box(P(au + aw * 0.5 - 0.15, y, av), Vector3(0.25, fh - 0.3, ad - 0.4), BRICK)
		_box(P(au - aw * 0.5 + 0.15, y, av), Vector3(0.25, fh - 0.3, ad - 0.4), BRICK)
	# lift core + stair shaft
	_box(P(au + aw * 0.5 - 3.0, top * 0.5 + 1.5, av - f * (ad * 0.5 - 2.5)), Vector3(4.0, top + 3.0, 4.0), CONCRETE.lightened(0.1))
	# green shade net + scaffolding on the front
	var front_v := av + f * (ad * 0.5 + 0.9)
	for i in 15:
		var cu := au - aw * 0.5 + aw * i / 14.0
		_box(P(cu, top * 0.5, front_v), Vector3(0.09, top + 0.8, 0.09), Color("a07a3c"))
	for k in range(1, int(top / 1.8) + 1):
		_box(P(au, k * 1.8, front_v), Vector3(aw, 0.08, 0.08), Color("a07a3c"))
	for k in range(0, 4):
		_box(P(au - aw * 0.5 + aw * (k + 0.5) / 4.0, top * 0.35, front_v - f * 0.1), Vector3(aw / 4.0 - 0.3, top * 0.6, 0.04), Color(0.2, 0.45, 0.24))
	# tower crane
	var cx := au - aw * 0.5 - 4.0
	_box(P(cx, 17.0, av), Vector3(0.7, 34.0, 0.7), Color("f2b21a"))
	_box(P(cx + 9.0, 34.4, av), Vector3(28.0, 0.8, 0.7), Color("f2b21a"))
	_box(P(cx - 6.5, 33.2, av), Vector3(3.0, 1.6, 1.4), Color("6b6b6b"))
	_box(P(cx + 14.0, 30.0, av), Vector3(0.06, 8.0, 0.06), Color("222222"))
	_coll(au, top * 0.5, av, aw, top, ad)
	_coll(cx, 5.0, av, 1.4, 10.0, 1.4)

# --- playground, garden, temple, median, cars, hills
func _playground() -> void:
	var pg: Dictionary = d["playground"]
	var c: Array = pg["c"]
	var cu := float(c[0]); var cv := float(c[1]); var r := float(pg["r"])
	var cm := CylinderMesh.new()
	cm.top_radius = r - 1.5; cm.bottom_radius = r - 1.5; cm.height = 0.05; cm.radial_segments = 32
	_mi(cm, w._pbr("ground037", 4.0, Color("e0cf9e")), P(cu, 0.07, cv), false)
	# hedge ring
	var n := 40
	for k in n:
		var a0 := TAU * k / n
		var hu := cu + cos(a0) * (r - 0.6)
		var hvv := cv + sin(a0) * (r - 0.6)
		_box(P(hu, 0.55, hvv), Vector3(3.4, 1.1, 1.1), Color(0.2, 0.45, 0.2), -a0 + PI * 0.5)
	# net
	var nu: Array = pg["net_u"]
	var nu0 := float(nu[0]); var nu1 := float(nu[1])
	for pu: float in [nu0, nu1]:
		_box(P(pu, 1.3, cv), Vector3(0.14, 2.6, 0.14), Color("dcdcdc"))
	var net := BoxMesh.new()
	net.size = Vector3(nu1 - nu0, 1.1, 0.03)
	var nm := StandardMaterial3D.new()
	nm.albedo_color = Color(0.92, 0.92, 0.92, 0.5)
	nm.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	nm.cull_mode = BaseMaterial3D.CULL_DISABLED
	_mi(net, nm, P((nu0 + nu1) * 0.5, 1.85, cv), false)
	_box(P((nu0 + nu1) * 0.5, 2.42, cv), Vector3(nu1 - nu0, 0.08, 0.08), Color.WHITE)
	# small goals + benches + slide
	for sg: float in [-1.0, 1.0]:
		_box(P(cu + sg * 14.0, 0.0 + 1.0, cv - 14.0), Vector3(0.1, 2.0, 5.0), Color.WHITE)
		_box(P(cu + sg * 17.0, 1.0, cv + 12.0), Vector3(1.6, 0.6, 0.6), Color("5a4636"))
	_box(P(cu - 16.0, 1.2, cv + 6.0), Vector3(2.4, 0.2, 5.0), Color("e8403a"), 0.0, 0.0)
	_box(P(cu - 16.0, 0.6, cv + 3.6), Vector3(2.4, 1.2, 0.2), Color("f2c230"))
	_text("PLAYGROUND", P(cu, 6.0, cv + r), 0.02, Color("fff3c8"))
	_coll(cu - 16.0, 1.0, cv + 6.0, 2.6, 2.0, 5.2)

func _garden_temple() -> void:
	var g: Dictionary = d["garden"]
	var gu := float(g["u"]); var gv := float(g["v"]); var gw := float(g["w"]); var gd := float(g["d"])
	_rect_flat(gu - gw * 0.5, gv - gd * 0.5, gu + gw * 0.5, gv + gd * 0.5, 0.06, Color(0.34, 0.55, 0.26))
	_rect_flat(gu - 1.5, gv - gd * 0.5, gu + 1.5, gv + gd * 0.5, 0.075, Color("d9cba0"))
	_rect_flat(gu - gw * 0.5, gv - 1.5, gu + gw * 0.5, gv + 1.5, 0.075, Color("d9cba0"))
	var fl_xf := {"flower_redA": [], "flower_yellowA": [], "flower_purpleA": []}
	_rng.seed = 77
	var kinds := fl_xf.keys()
	for i in 90:
		var lu := gu + _rng.randf_range(-gw * 0.45, gw * 0.45)
		var lv := gv + _rng.randf_range(-gd * 0.45, gd * 0.45)
		if absf(lu - gu) < 3.0 or absf(lv - gv) < 3.0:
			continue
		(fl_xf[kinds[i % 3]] as Array).append(transform * Transform3D(Basis(Vector3.UP, _rng.randf() * TAU).scaled(Vector3.ONE * 2.4), P(lu, 0.0, lv)))
	for k in fl_xf:
		w._scatter("res://assets/kenney/nature/%s.glb" % k, fl_xf[k])
	_text("GARDEN", P(gu, 5.0, gv - gd * 0.5 + 2.0), 0.02, Color("fff3c8"))
	var t: Dictionary = d["temple"]
	var tu := float(t["u"]); var tv := float(t["v"]); var tw := float(t["w"])
	_box(P(tu, 0.4, tv), Vector3(tw, 0.8, tw), CREAM)
	_box(P(tu, 0.9, tv), Vector3(tw - 1.5, 0.3, tw - 1.5), YELLOW)
	_box(P(tu, 2.6, tv), Vector3(5.4, 3.4, 5.4), Color("f6efe0"))
	var sh := 4.0
	for k in 5:
		var s := 4.6 - k * 0.85
		_box(P(tu, 4.7 + k * 0.9, tv), Vector3(s, 0.95, s), Color("f1ddb0") if k % 2 == 0 else Color("f08a2a"))
	_box(P(tu, 9.5, tv), Vector3(0.5, 0.7, 0.5), Color("e8b823"))
	_box(P(tu, 10.6, tv), Vector3(0.08, 1.6, 0.08), Color("a07a3c"))
	_box(P(tu + 0.45, 11.0, tv), Vector3(0.9, 0.55, 0.05), Color("f06a1a"))
	_box(P(tu, 1.8, tv - tw * 0.5 + 1.4), Vector3(1.4, 2.0, 0.1), Color("3a2a22"))
	_coll(tu, 3.0, tv, tw, 6.0, tw)

func _median() -> void:
	var md: Array = []
	for r in d["roads"]:
		if r["id"] == "main_in":
			md = r["pts"]
	var vend := float((md[md.size() - 1] as Array)[1])
	_box(P(0.0, 0.12, vend * 0.5), Vector3(2.0, 0.24, vend), Color("a89468"))
	for sg: float in [-1.0, 1.0]:
		_box(P(sg * 0.95, 0.15, vend * 0.5), Vector3(0.2, 0.3, vend), Color("d6d0c0"))

func _cars() -> void:
	var by_model := {}
	for c in d["cars"]:
		var m := str(c[3])
		if not by_model.has(m):
			by_model[m] = []
		var xf := transform * Transform3D(Basis(Vector3.UP, float(c[2]) + PI).scaled(Vector3.ONE * 1.75), P(float(c[0]), 0.575, float(c[1])))
		(by_model[m] as Array).append(xf)
		_coll(float(c[0]), 0.7, float(c[1]), 2.3, 1.4, 4.4, float(c[2]))
	for m in by_model:
		w._scatter("res://assets/kenney/cars/%s.glb" % m, by_model[m])

func _hills() -> void:
	for h in d["hills"]:
		var hu := float(h["u"]); var hv := float(h["v"]); var hw := float(h["w"]); var hh := float(h["h"])
		var ridge: bool = h["kind"] == "ridge"
		var st := SurfaceTool.new(); st.begin(Mesh.PRIMITIVE_TRIANGLES)
		var steps := 36
		var dep := 90.0 if ridge else hw * 0.45
		for k in steps:
			var t0 := float(k) / steps
			var t1 := float(k + 1) / steps
			var rows: Array = []
			for tt: float in [t0, t1]:
				var x := (tt - 0.5) * hw
				var prof := (1.0 - pow(absf(tt - 0.5) * 2.0, 2.0)) if not ridge else (0.55 + 0.45 * sin(tt * 17.0) * sin(tt * 5.3 + 1.0))
				rows.append([x, maxf(prof, 0.0) * hh])
			var a: Array = rows[0]
			var b: Array = rows[1]
			var q := [Vector3(a[0], 0, 0), Vector3(b[0], 0, 0), Vector3(b[0] * 0.6, b[1], -dep * 0.45), Vector3(a[0] * 0.6, a[1], -dep * 0.45)]
			var q2 := [Vector3(a[0] * 0.6, a[1], -dep * 0.45), Vector3(b[0] * 0.6, b[1], -dep * 0.45), Vector3(b[0] * 0.8, 0, -dep), Vector3(a[0] * 0.8, 0, -dep)]
			for qq in [q, q2]:
				for idx in [0, 1, 2, 0, 2, 3]:
					st.set_normal(Vector3.UP)
					st.set_color(Color("8d8a82").lerp(Color("a9b5c0"), 0.35))
					st.add_vertex(qq[idx])
		var mesh := st.commit()
		var mi := MeshInstance3D.new()
		mi.mesh = mesh
		mi.material_override = _mat_solid
		mi.position = P(hu, -1.0, hv)
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		add_child(mi)
